@echo off
echo Stopping any previous RayCaster Server...
taskkill /FI "WINDOWTITLE eq RayCaster Server" /F >nul 2>&1
echo Starting RayCaster Server...
start "RayCaster Server" node server.js
echo Waiting for server to initialize...
timeout /t 2 /nobreak >nul
echo Opening Game...
start http://localhost:8000
exit
